egraphs-good/egglog

tests/eqsolve.egg, tests/pathproof.egg, tests/unify.egg
An example 
- Proof carrying path connectivity
- Unification
- Equation solving
=> Added some more examples to tests

src/gj.rs
This was low-hanging fruit identified by some benchmarks. For the associativity benchmark @yihozhang wrote up:
```
(datatype Math
(Var i64)
(Add Math Math)
)
(define start (Add (Var 1) (Add (Var 2) (Add (Var 3) (Add (Var 4) 
(Add (Var 5) (Add (Var 6) (Add (Var 7) (Var 8)))))))))
(rewrite (Add x y) (Add y x))
(rewrite (Add x (Add y z)) (Add (Add x y) z))
(run 8)
(define end (Add (Var 8) (Add (Var 7) (Add (Var 6) (Add (Var 5) 
(Add (Var 4) (Add (Var 3) (Add (Var 2) (Var 1)))))))))
(check (= start end))
```
Some anecdotal numbers from my workstation:
Before:
```
target/release/egg-smol assoc.egg  9.28s user 0.03s system 98% cpu 9.480 total
```
After:
```
target/release/egg-smol tests/assoc.egg  2.75s user 0.02s system 96% cpu 2.874 total
```
=> Pool allocations made during inner loop for GJ.

tests/typeinfer.egg
Thanks for catching these type errors! The new type errors produced by action compilation are very helpful! It also implies this demo program right now is not well tested, and more tests are definitely needed.
=> Fixing type errors in type inference

README.md, src/sort/rational.rs
List talk and paper, as well as basic syntax.
=> Add basic documentation

src/gj.rs
This is a draft supporting constant constraints in GJ. I think we'd want to clean this up a bit before submission, but it could serve as a useful proof of concept. With this change, the program in #124 fails (as expected).
The basic idea here is to add a degenerate variant of the `Intersect` instruction that just does a single lookup on a trie at a particular constant value. We generate one of these instructions per constant constraint in the query, and all of these constant instructions are run before any `Intersect`s are.
The alternative would be to munge these constraints into the existing primitive constraints, but this seems more straightforward and efficient.
=> Add support for constaining by constants in GJ

src/main.rs
Sorry, #199 doesn't handle `proofs` mode properly.
This PR fixes it.
=> Fix parsing error message fix #199

src/termdag.rs
=> Format #214

tests/integer_math.egg
Add a test like `math.egg` but for integers instead of rationals.
=> Add integer math test

src/lib.rs
This PR sorts the rules by time, and also adds a number of matches statistic.
=> Better statistics for runs

src/lib.rs
=> Fix ambiguity in `core` module

README.md
=> Add Neovim plugin in README.md

Cargo.lock, Cargo.toml, rust-toolchain.toml, src/gj.rs
Needed for eggcc to be compatible with bril2json
=> bump regex to 1.10

src/lib.rs, web-demo/src/lib.rs, web-demo/static/index.html, web-demo/static/worker.js
=> Easier access to logs for the web demo

tests/resolution.egg
Noticed while playing around with egg during Marktoberdorf :)
=> Fix typo in web demo example

web-demo/static/index.html
=> Fix margin of <select>

CHANGELOG.md, Cargo.lock, Cargo.toml, web-demo/Cargo.toml
Pending https://github.com/egraphs-good/egraph-serialize/pull/17
=> Prepare for v0.3.0

src/lib.rs
https://github.com/egraphs-good/egglog/pull/442/files/8ae1427f67040e833526495678fa91351a17af00#r1807931895
=> Add `get_sort` back

src/ast/parse.rs
This PR cleans up the parsing of options such as `:ruleset` in `ast::parse::command`. This ensures that all the commands parse options in the same way.
Note: there are still some places where options are parsed manually; these are due to variadic constructs, such as `run`, where if we don't parse the second-to-last child as an option then we need to parse all the children as sorts.
=> Small: clean up option (`:`) parsing

.github/workflows/deploy.yml
Title. This should fix main, which is currently failing.
=> Fix deprecation of actions/upload-artifact/v3

CHANGELOG.md, Cargo.lock, Cargo.toml, web-demo/Cargo.toml
Forget to update the version number in my last PR oops
=> second attempt releasing 0.4.0

Cargo.lock, Cargo.toml, src/function/mod.rs, src/lib.rs, tests/complex-merge-func.egg, tests/complex-merge-prim.egg
Translate egglog expressions to the MergeFn enum in the backend. (Want to test before merging)
=> Wire in expanded merge functions

Cargo.lock, Cargo.toml, src/function/mod.rs
Pulls down subsumption and the bugfix for `MergeFn::AssertEq`.
=> Version bump

Cargo.lock, Cargo.toml, src/function/mod.rs, src/lib.rs, src/sort/add_primitive/src/lib.rs, src/sort/fn.rs, src/sort/map.rs, src/sort/multiset.rs, src/sort/set.rs, src/sort/vec.rs, src/typechecking.rs
This PR does cleanup and implements a sketchy but test-passing version of `unstable-fn`.
=> Sketchy `unstable-fn` support in new backend

src/function/mod.rs, src/lib.rs
Fixes the `test_subsume_custom` test.
=> New backend: fix test_subsume_custom

tests/repro-new-backend-prims.egg
=> Fix repro-new-backend-prims.egg

web-demo/src/lib.rs
=> Use newline character instead of <br>

Cargo.lock, Cargo.toml, src/ast/mod.rs, src/core.rs, src/lib.rs, src/prelude.rs, src/scheduler.rs
=> Scheduler interface with `choose`

Cargo.lock, Cargo.toml, Makefile, src/lib.rs, src/typechecking.rs
- Remove Makefile collects
- Bump dependency versions
- Resolve the "missing spans" comment
=> Backend merge follow up

src/sort/add_primitive/src/lib.rs
=> remove redundant clone of exec_state
