- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- tests/stratified.egg
Stratification is a useful thing in datalog. A simple mechanism to help enable it is to allow the clearing of current rules while retaining the current database. Alternatives could include `(push-rules)` / `(pop-rules)` or turning on / off named rule sets. This command would be more meaningful when combined with `(saturate)`,  negation and aggregates, but is the first simple step towards those features.
> Clear-rules

- src/ast/parse.lalrpop
Was missing a way to use `=` from Datalog syntax. Perhaps I should enable the chained `=` form in the parser, but I'm not sure how to do this.
> Added `=` to datalog syntax

- Cargo.toml
- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- src/value.rs
- tests/datalog.egg
Minimal version of adding a query command. The current printing is subpar, it is unclear that we want to add sexp as a dependency. To be discussed.
Possibly when printing the query of an eclass id, we also want to extract a term for it rather than print the id. In this case, query may subsume the extract command.
The command `(query ((path x y)))` will print the entire table `path`. 
It is noted in a previous comment that `(query ((path 1 2)))` subsumes the capabilities of `(check (path 1 2))`
It is necessary but not done that we print what element of the sexp corresponds to which pattern variable
> Initial Query Command

- tests/points-to.egg
Translate one of the pure-datalog queries from "From Datalog to Flix" into egg-smol. Happy to move to a draft if it'd be better to skip straight to either of:
* The more sophisticated lattice-based examples from the flix paper (e.g. IFDS). These will require some additional merge functions other than those that are already implemented for primitives.
* An "egg-only" example of combining dataflow analyses with rule-based optimizations, where the egg-smol program allows the result of peepholes to refine (say) an escape analysis and vice-versa. I don't know of obvious areas here to start with, but if something like this was part of the broader "compositional analyses" motivation I'd appreciate a pointer.
> Add simple points-to analysis test case

- tests/typecheck.egg
It turns out type checking does not require injectivity (the app rule does it manually).
> simplify type checking and more examples

- Cargo.toml
- src/ast/expr.rs
- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/extract.rs
- src/gj.rs
- src/lib.rs
- src/sort/i64.rs
- src/sort/macros.rs
- src/sort/map.rs
- src/sort/mod.rs
- src/sort/rational.rs
- src/sort/string.rs
- src/sort/unit.rs
- src/typecheck.rs
- src/unionfind.rs
- src/value.rs
- tests/interval.egg
- tests/map.egg
This gives the ability to add new sorts (and primitives) the e-graph. EqSorts (union-able sorts) are still special, but they might not have to be for long.
> Make sorts extensible

- tests/bdd.egg
Binary Decision Diagrams are if-then-else trees/ compressed tries that hash cons their subexpressions
This is easily expressible in the facilities provided. Everything in egg-smol is automatically shared
and Compression is easily expressible as a rule.
They are a notion of first class set useful for certain classes of uniformly describable sets.
https://en.wikipedia.org/wiki/Binary_decision_diagram
https://www.lri.fr/~filliatr/ftp/publis/hash-consing2.pdf Type-Safe Modular Hash-Consing - Section 3.3
> Binary Decision Diagrams

- tests/nbe.egg
Maybe this is right.
In a sense it is barely using any egraph powers. It is not clear where other equational theories might go (into Value?).
I suspect the separation between Terms, Values and Neutral values is crucial. Terms are adts, pure syntax. Values are something more semantic and obey interesting equations.
Heavily based on the implementations here:
- https://github.com/AndrasKovacs/elaboration-zoo/blob/master/01-eval-closures-debruijn/Main.hs 
- https://proofassistants.stackexchange.com/questions/900/when-should-i-use-de-bruijn-levels-instead-of-indices
- https://www.andres-loeh.de/LambdaPi/LambdaPi.pdf
> Normalization by Evaluation

- src/lib.rs
Currently the AC test fails because of the bailing threshold (it assumes a SimpleScheduler).
> add more perf stats and increase bailing threshold

- src/lib.rs
- src/unionfind.rs
This is a hacky solution to bail when saturation. I think we should refactor this later (and probably not merge it for now), but this is useful for benchmarking against Datalog, which always runs to saturation.
> Bailing when saturation

- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
print-size is a simple command that lets the user verify the program produces something reasonable without looking into the functions.
> Add print_size command

- src/lib.rs
This is a low hanging fruit in improving rebuilding. Since right now the database is created afresh during each rebuilding, most time is spent on inserting tuples into a new database. However, we only need to process those that are changed.
Before:
```
Geomean egglog/souffle: 0.5349996183864182
Total egglog/souffle: 0.687601368899584
```
After:
```
Geomean egglog/souffle: 0.4056677316834581
Total egglog/souffle: 0.4405201946577985
```
~Also, there are still many opportunities for optimization: the rebuilding in this PR uses many small vectors. ~1/2 time of the rebuilding is spent on malloc/free.~ Not the case after using smallvecs with the latest main
> Improving rebuilding

- src/lib.rs
- src/main.rs
I don't know how IO pure run_command should be. From the perspective of building external tools that communicate to egg-smol via stdin stdout, it would probably be nice to make these errors s-expressions also.
> Removed print to stdout except from print commands

- src/gj.rs
- src/lib.rs
- src/main.rs
This fixes the backoff scheduler and allows users to specify --naive to disable SN evaluation
> Fix backoff and allow naive evaluation as an option

- src/lib.rs
This PR makes extracts defining an expression into a public function.
I am working on Python bindings for this package and wanted to expose this in Python, for example, [to recreate the `eqsat_basic` example](https://egg-smol-python.readthedocs.io/en/latest/explanation/compared_to_rust.html#low-level-bindings-api).
Alternatively, `eval_expr` and  a "get function" methods could be exposed to recreate the same logic.
> Create public define function

- tests/resolution.egg
Traditional resolution theorem provers maintain a clause database of formulas in Conjunctive Normal Form (CNF is a big And of Ors). Each clause is a set of positive and negative literals. 
The prover saturates this set by taking two clauses  {a}\/c1  {not a}\/c2 and creating a new clause c1 \/ c2. Clauses also are pruned by simplications, unit propagation, and subsumption. These systems use sophisticated term indexing to find matching clauses.
A natural question is whether egglog's saturation and term indexing gives a leg up towards building one of these systems. A programmable one even, with built in support for equality reasoning
- Resolution is provided by a join
- unit propagation is an equation solving process and egraph substitution
- Clause Simplification is provided by rewrite …
> Resolution Style Theorem Prover

- src/lib.rs
This PR is a followup to #56, which makes more of the API public. There is now enough made public to expose all the same functionality as exposed in the text command interface through Python. The corresponding Python PR is https://github.com/metadsl/egg-smol-python/pull/4.
I opted to not expose the `Value`s to Python at all, relying on these higher-level function calls instead. I saw that there was a comment on the `Value` to make it private at some point.
> Make more of the API public

- src/lib.rs
This PR is another follow-up to #56  and #62, which extract the behavior to name a sort, like `(sort StringSet (Map Var i64))`. The function `declare_sort` was already taken, to add a user-defined sort, so I wasn't sure what to call this. Happy to rename if you have other suggestions.
> Extract declaring a sort alias into a pub fn

- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/typecheck.rs
- tests/matrix.egg
This PR renames the "define" action to "let", which makes it clearer the difference between the define command and this action (closes #67).
Even though this action now doesn't conflict in name with the "define" command, it is still not allowed at the top level of the text file, because, AFAIK, it would be a no-op there.
> Rename define action to let

- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- tests/birewrite.egg
When doing theorem proving there are equational axioms which go both ways. Copying and pasting them twice is annoying and clunky. A simple birewrite command is silly but really nice. This could possibly be subsumed by some kind of macro system
> BiRewrite Command

- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- tests/until.egg
For proving purposes, it's nice to state a condition for which you want the process to stop at rather than manually searching for a good iteration limit.
This adds an optional flag `:until (= foo bar)` to the `run` command, which uses the same logic essentially as the `check` command.
If you need more sophisticated stop conditions, consider using a `(relation relation stop (unit))` with rules filling it in with different stop conditions of interest.
I also removed some redundancy in the parser which was a holdover from when primitives were lexically different from user defined functions. Now user defined functions with operator like names are enabled. This change was orthogonal to the main point of this pull request, but I was sick of writing `mul` in my example.
> Add User Defined Stopping Condition

- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- tests/calc.egg
[Dafny](http://dafny.org/dafny/DafnyRef/DafnyRef.html#sec-calc-statement) and [Lean](https://github.com/leanprover-community/leanprover-community.github.io/blob/newsite/templates/extras/calc.md) both have a notion of a calculational proof. Agda also has a style like this.
This is a proof command that allows one to break up a proof query with user given hints.
```
(calc ((a G) (b G))
(* (* b (* (inv a) a)) (inv b))
(* b (inv b))
(I)
)
```
It works by 
1. pushing the egraph
2. inserting fresh constants (eids) as `a` and `b`. This is a way of asking a universally quantified question.
3. inserting pairs of subsequent entries of the calc command.
4. running until the two are found to be equal.
5. popping all of this out of the egraph
When I was trying to debug why my category theory proofs in …
> Calc command

- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- tests/include.egg
Include is a poor man's modules.
The include command allows at least some structuring and reuse. Combinations of including and clear-rules can be used to achieve an effect similar to rule sets. Axiom files can include from theories they refine. Diamonds will have a bad effect though.
In particular, I am using this because I'm hand writing some additional handwritten stuff to generated egglog files which keep getting regenerated as I find new problems. Currently the multiple files on the command line makes a new egraph for each, which is perhaps not what one would want in some situations.
It might be possible or wise to import files under a new namespace with structured ids. 
Z3 supports an include command, although I don't see it in the smtlib spec
> Include Command

- src/ast/parse.lalrpop
These are remnants from when sorts and primitive constants were hard coded into the parser. Leaving them in removes the ability of a user to use these keywords.
> Remove unnecessary restrictions in parser

- tests/combinators.egg
Basic attempt at encoding a basic lambda calculus into S/K/I combinators. The test is structured to take a simple baseline AST with only primitive rewrites encoded on the AST. It then "mechanically" translates that AST to a richer datatype with S/K/I, implements substitution there, and then maps back to the source AST. 
A few notes:
* The two-type pattern could serve as a model for mechanically implementing substitution for a language with names without breaking other rewrites defined on the AST. Could be worth comparing with other approaches like explicit substitution that seem implementable in egg-smol.
* The classic presentation for translating a named lambda calculus involves negation ("fire this rewrite if variable x is not free in expression e"). This example hacks around it, but at …
> Combinator test

- src/ast/parse.lalrpop
(define foo 1.2e-5)
[INFO ] Defined foo: F64Sort { name: "f64" }
(extract foo)
[INFO ] Extracted with cost 0: 0.000012
(define bar 1.2e20)
[INFO ] Defined bar: F64Sort { name: "f64" }
(extract bar)
[INFO ] Extracted with cost 0: 120000000000000000000
(define baz 1.23)
[INFO ] Defined baz: F64Sort { name: "f64" }
(extract baz)
[INFO ] Extracted with cost 0: 1.23
> Support 1.2e10 float syntax

- build.rs
- src/proofs.rs
- src/typechecking.rs
- tests/fail-typecheck/unbound.egg
- tests/files.rs
Previously, unbound variables are caught by the SSA validity pass instead of the typechecker.
This is a simple fix
> Fix typecheck bug

- src/lib.rs
This PR adds an API for retrieving the results of the few commands that produce values: extracting expressions and triggering runs.
This works by saving the last values of these when they are created on the e-graph and allowing users to take them. While I assume this does add some overhead for existing egg-smol users, I don't imagine it should be very substantial, since I am only ever saying a maximum of one result at a time.
I am using this in the Python bindings to retrieve these results after a use executes a command. See  https://github.com/metadsl/egg-smol-python/pull/14 for where I am currently using this branch.
I made changes in the Python bindings to only interface at the level of command execution, instead of exposing individual e-graph methods, as I was doing previously. I did …
> Expose results after running commands

- src/typecheck.rs
I am looking through to better understand the difference between setting and unioning and I thought it might be useful to clarify this error message.
According to the ["Better Together" paper](https://arxiv.org/abs/2304.04332) only user-defined sorts can be unionized, not builtin types:
> Crucially, values of user-defined sorts (as opposed to base types) can be unified by the union action.
> Clarify error message for unioning base types

- src/ast/desugar.rs
- src/lib.rs
- src/typecheck.rs
- tests/semi_naive_set_function.egg
Fixing the problem in issue[#93](https://github.com/mwillsey/egg-smol/issues/93), that in semi-naive eval, the change happens in the right-hand-side in set operation should affect the evaluation, but being ignored due to semi-naive. The fix was to add a new rule while meeting setting to a Call, add one more equal relation to the body part of the rule in the desugar_command phase, as well as let binding since they might bind variables in the Call.
> Semi naive fix

- src/extract.rs
- src/lib.rs
- src/sort/f64.rs
- src/sort/i64.rs
- src/sort/map.rs
- src/sort/mod.rs
- src/sort/rational.rs
- src/sort/set.rs
- src/sort/string.rs
- src/sort/unit.rs
- src/sort/vec.rs
- tests/fusion.egg
This PR resolves a bug that previously triggered an error when trying to extract a set or map with a user-defined equality sort as its value. The issue stemmed from the fact that equality sorts were not properly handled in certain circumstances.
To fix this, I passed the egraph into the make_expr function on each sort. This allows sorts that may contain equality sorts to call the extract method and load those values when necessary.
I also add added a demonstration of this feature to provide a working example and test case to the `tests/fusion.egg` file.
During this process, I refactored some parts of the code to use the `extract` method. This ensures that all code determining whether a value is an equality sort uses the same logic.
These changes ensure that all code determining whether a …
> Fix bug when extracting sets/maps with equality sort values

- src/function/index.rs
- src/function/mod.rs
- src/function/table.rs
- src/lib.rs
Fixes a couple small bugs:
The method `rebuild_at` was slightly wrong in a couple ways:
1. Merge functions should run on canonicalized values, meaning we should take the previous value in a given function row and canonicalize it before merging it.
2. We should not unconditionally remove the old row in a table: the keys to a row may not have changed. Instead, run the merge function first and only remove the old row if needed. 
On top of that there was (I think) an unintentional variable shadowing in the `add` method for "composite" indexes.
Fixes #121
> Fix subtleties in rebuilding

- src/ast/parse.lalrpop
- src/lib.rs
- src/main.rs
Some more tweaks the the herbie tutorial- the main one is to allow `[` instead of `(` everywhere, as syntax sugar. In the talk I use `[` for evaluating primitives.
> More tweaks for the herbie tutorial

- src/sort/vec.rs
- src/typechecking.rs
- tests/vec.egg
* Fixes a typo so that the `Vec` sort will register a Vec instead of a Set
* Fixes the function name for extracted vecs
* Adds test for existing Vec methods
* Add vec get and length (closes #152)
> Vec fix, tests, and improvements

- src/sort/string.rs
- tests/string.egg
This PR adds support for string concatenation and a test for it. It uses the `+` function which is already overloaded for integers and floats.
> Add string concatenation

- README.md
README links to https://egglog-python.readthedocs.io/en/latest/, but that page 404s.
It appears these docs are at https://egg-smol-python.readthedocs.io/en/latest/?
> Update README Python binding doc link

- src/lib.rs
This PR adds support for third party packages to add their own sorts.
I am using it in https://github.com/metadsl/egglog-python/pull/31 to add a custom `PyObject` sort, with primitive operations for executing code and converting.
> Add support for third party sorts

- src/serialize.rs
Switches the check in the serialize to use the `number_underscores` variable instead of hardcoding them so it is more accurate.
Discovered when adding test files to egraph-serialize with `--save-json` CLI command https://github.com/egraphs-good/egraph-serialize/pull/4
> Fix serialize checking for temp name

- README.md
I think this was an oversight when removing `define` in #176.
> Change remaining README uses of `define` to `let`

- src/lib.rs
- src/termdag.rs
Follow up on @oflatt's #176  which introduces a `TermDag` and exposes it via the `ExtractReport`.
This PR makes the `TermDag` public and also makes both fields on it public.
This is needed to update the `ExtractReport` bindings in Python (see https://github.com/metadsl/egglog-python/pull/42).
I wasn't sure whether to expose the `TermDag` and `Term` types at the top level module (what I did) or whether to expose the `egglog::termdag` module as a whole.  I am happy to change it if you prefer.
> Make termdag public

- README.md
- src/sort/f64.rs
- src/sort/i64.rs
- tests/f64.egg
- tests/i64.egg
Adds a `to-string` function for floats and ints.
For floats, it uses the debug form instead of the `to_string` so that the decimal place is always printed.
> Add to-string function for floats and ints

- src/main.rs
This PR makes a parse error message more readable
Before 
```
[ERROR] Unrecognized token `)` found at 169:170
Expected one of r#"(([[:alpha:]][\\w-]*)|([-+*/?!=<>&|^/%_]))+"# or r#"(-)?[0-9]+"#
```
After
```
[ERROR] Unrecognized token `)` found at ../tmp/path.egg:11:5:../tmp/path.egg:11:6
Expected one of r#"(([[:alpha:]][\\w-]*)|([-+*/?!=<>&|^/%_]))+"# or r#"(-)?[0-9]+"#
```
This will be very helpful for new users like me.
> Show parse error's line number and column number

- src/termdag.rs
Wrote some docs.
I also deleted this old comment:
``` rust
// users can't construct a termnode, so just
// look it up
```
which I believe to be wrong. `Term` is exported publicly via `src/lib.rs`:
``` rust
pub use termdag::{Term, TermDag};
```
So users *can* construct `Term`s by hand.
Because of this, I included in the documentation for various methods what the
behavior of the current implementation is when given malformed `Term`s.
> Document src/termdag.rs

- tests/matrix.egg
Remove `(let ...)` in the actions for the rules in the matrix example, since they are unnecessary, and make the example more confusing.
> Remove lets in matrix demand

- src/ast/expr.rs
- src/ast/parse.lalrpop
- src/extract.rs
- src/lib.rs
- src/termdag.rs
- tests/terms.rs
@oflatt mentioned he would prefer callers not to be able to construct Terms directly, but still be allowed to pattern match on them. I don't think exactly that is possible in Rust, but here is an alternative. We make the indices into the DAG opaque, but we leave the Term enum fully public. That way the API kinda pushes you toward only constructing one layer of a term at a time, which is exactly how it should be used. Oliver, what do you think?
This PR also adds a bunch of tests about terms (and a bit about exprs). If we decide not to make the term index change, I can split this PR to just merge the tests.
There is also a test that demonstrates how a caller can still shoot themselves in the foot by taking TermId from one TermDag and passing it to a different TermDag. This could cause wrong …
> Make TermDag indices opaque, write tests for TermDag

- README.md
Web Demo badge link pointed to the docs, not the web demo. I'm assuming that was not intentional!
> Fix Web Demo badge link

- src/ast/mod.rs
In #176 the `ExtractCommand` is now created with `query-extract` instead of `extract`.
> Fix to_sexp for extract

- src/lib.rs
- src/termdag.rs
Follow up from https://github.com/egraphs-good/egglog/pull/202 to expose the TermID so that we can create/access them in the Python bindings.
See #192 for the original PR which made these public.
> Expose TermID

- src/lib.rs
The old name was confusing because `Expr` refers to a different data structure
without sharing.
cc @oflatt
> Rename ExtractReport::{expr -> term}

- README.md
There is now a full egglog stream and the egg-smol topic is not used anymore.
> Update link to zulip chat

- src/termdag.rs
Now you can write arbitrary patterns in `match_term_app!`. I will use this in
eggcc as I refactor CFG conversion to use terms instead of expressions.
> Make match_term_app! support arbitrary patterns

- src/ast/desugar.rs
- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/lib.rs
- tests/math-microbenchmark.egg
This PR improves the run report to report timing information for individual rules and also for rulesets.
It also adds, in addition to the existing run report for the most recently run schedule, a report that collects statistics across all the runs.
> Better rule and ruleset timing statistics

- src/ast/desugar.rs
Hi, we have been troubleshooting a name resolution bug and discovered that ﻿`egglog` has a regression case. You can find more details at https://github.com/rust-lang/rust/pull/115269.
In this context, `﻿crate::ast::Rule` should be overshadowed by ﻿`crate::Rule` when `﻿crate::*` is used.
> fix: use single import for `Rule`

- src/gj.rs
This PR breaks out the core loop of seminaive generic join into a function
> Small gj refactor

- src/sort/i64.rs
- src/sort/string.rs
- tests/string.egg
This PR adds two new methods for strings, counting the number of occurrences of a substring and replacing a substring.
> Add count match and replace string functions

- src/sort/vec.rs
- tests/vec.egg
Add primitive `(vec-set vec index val)`
Added basic test to [`tests/vec.egg`](https://github.com/egraphs-good/egglog/blob/cec39afc8100a167cc9e8326825c229db2485a8c/tests/vec.egg)
> Add `vec-set`

- src/lib.rs
- src/main.rs
- src/serialize.rs
- tests/files.rs
- web-demo/src/lib.rs
Fixes #244
You can see that in this example, splitting the primitive outputs makes the structure of the graph **much** clearer and the edges are legible, even though it is just as large:
> Add option serialization option to separate primitive results into their own e-classes

- src/lib.rs
#225 introduced a bug with preserving statistics when popping, which doubles the timing statistics each time you pop. This PR fixes that.
Closes #240
> Fix bug in statistics tracking when popping

- README.md
Resolves the question in #229 by stating that merge functions must be monotonic, otherwise there is undefined behavior.
> Clarify that merge should be monotonic

- src/ast/desugar.rs
- src/ast/mod.rs
- src/ast/parse.lalrpop
Fix #243 
This PR
- Fix `Command::Extract` to contain `Expr` instead of `Fact` because inputting `Fact::Eq` into it leads to a runtime error
- Disallow variable and literal itself as a fact
- Since `Expr::Call` doesn't have its own type yet, `Fact` still has an `Expr`.
> Update Fact accept CallExpr instead of Expr

- src/sort/vec.rs
Currently, `query-extract` for `vec` prints the reverse order of the argument
```
(sort IVec (Vec i64))
(let e (vec-of 1 2 3 4))
(query-extract e) ; => (vec-push (vec-push (vec-push (vec-push (vec-empty) 4) 3) 2) 1)
(check (= e (vec-push (vec-push (vec-push (vec-push (vec-empty) 4) 3) 2) 1))) ; fail
```
This PR fixes it and prints by `vec-of`
```
(sort IVec (Vec i64))
(let e (vec-of 1 2 3 4))
(query-extract e) ; => (vec-of 1 2 3 4)
(query-extract (vec-empty)) ; => (vec-empty)
(check (= e (vec-of 1 2 3 4))) ; OK
```
> Fix `query-extract` for `vec`

- src/value.rs
- tests/bool.egg
```
; Test bool's tag
(relation R (i64))
(function F (i64) bool)
(rule
((R i))
((set (F i) true))
)
(R 0)
(run 3)
```
fails
```
thread 'main' panicked at /home/hatoo/.cargo/git/checkouts/egglog-0aabc6dbd51d8ac4/a4559d2/src/function/mod.rs:183:17:
assertion `left == right` failed
left: "bool"
right: "Bool"
```
I guess this is because of a typo for bool's tag.
> FIx bool's tag symbol

- Cargo.lock
- Cargo.toml
- src/ast/expr.rs
- src/ast/mod.rs
`String` was a bad name. It corresponds more to symbol, since they are not wrapped in quotes.
This PR renames and updates to a newer version of my s-expr library that supports basic pretty printing
> Change s-expressions to use Symbol instead of String

- src/ast/expr.rs
- src/ast/mod.rs
This PR makes s-expression conversion public for convenience. This also allows users to pretty-print their s-expressions, which we need in the eggcc project.
> Make s-expression conversion public

- src/sort/i64.rs
- tests/bool.egg
This PR add `bool-=` function, which is similar to existing `bool-<` but missing. I found `bool-=` is needed in eggcc.
> Add integer equal boolean function

- src/function/mod.rs
- tests/eggcc-extraction.egg
egglog runs rebuilding until a fixed point: while egglog programs do not always terminate, rebuilding really always should.
@oflatt wrote an egglog program in which rebuilding didn't terminate. The idea was:
* Have some function `(function F (X X) X)`
* Make `F` the merge function of some other function `(function G (Y) X :merge (F old new))`
* Have an entry `(G arg1) => x`, `x`'s canonical member changes to `y`, and `arg1`'s canonical member changes to `arg2`. and we also have `(G arg2) => y`. 
During rebuilding, we notice that these two entries are equal (not just their keys, but also their values). In the current egglog code we _still run the merge function_,  creating a new entry `(G arg2) => (F y y)`. Furthermore, we union `y` and `(F y y)`. Then:
* We rebuild `F`, potentially …
> Short-circuit calls to merge functions with the same argument.

- README.md
The docs refer to an `vscode/egglog-1.0.0` or `vscode/vscode` directory, but neither of these exist: it should be (it seems) `vscode/eggsmol-1.0.0`.
> docs: fix reference to vs code plugin to match repo

- README.md
The Python docs have a new home, reflecting the updated Python package name. See https://github.com/egraphs-good/egglog-python/pull/92
> Update link to Python docs

- src/sort/set.rs
- tests/set.egg
Without these, we can't walk over a set nor match its contents.
See [tests/set.egg](https://github.com/rtjoa/egglog/blob/set-length-and-get/tests/set.egg) for examples.
> Add `set-length` and `set-get`

- src/terms.rs
fix #311 
There are 2 `Rule`s are defined in `crate::*`. Which are `crate::ast::Rule` and `crate::Rule`. And rustc is confused about it.
We should specify it clearly and I think it's good to remove `use crate::*;` and specify each `use`s
> Fix build on stable

- src/typechecking.rs
This one-line fix resolves the following compilation error I was getting on both `aarch64-darwin` and `x86_64-linux`:
```console
% cargo build -j 24 --target aarch64-apple-darwin --frozen --profile release
Compiling egglog v0.1.0 (/Users/connorbaker/Packages/egglog)
error[E0308]: mismatched types
--> src/typechecking.rs:169:43
|
169 |                 rule: self.typecheck_rule(rule)?,
|                            -------------- ^^^^ expected `&Rule`, found `&GenericRule<GlobalSymbol, GlobalSymbol, ()>`
|                            |
|                            arguments to this method are incorrect
|
= note: expected reference `&Rule`
found reference `&ast::GenericRule<GlobalSymbol, GlobalSymbol, ()>`
note: method defined here
--> src/typechecking.rs:319:8
|
319 |     fn …
```
> src/typechecking.rs: fix compilation failure with rustc 1.75.0

- src/lib.rs
- tests/repro-empty-query.egg
- tests/repro-equal-constant.egg
- tests/repro-equal-constant2.egg
Fixes #343, which demonstrated that queries without variables always match. This PR fixes it by handling the edge case, also adding a `SearchResult` abstraction.
> Fix queries with no variables firing without checking query

- src/lib.rs
- src/serialize.rs
Still keeps visualization defaults to limit for testing and to make more readable graphviz files.
Partially addresses #345
> Switch default serialization to output all nodes

- src/actions.rs
- src/ast/desugar.rs
- src/ast/expr.rs
- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/ast/remove_globals.rs
- src/constraint.rs
- src/core.rs
- src/function/mod.rs
- src/gj.rs
- src/lib.rs
- src/serialize.rs
- src/typechecking.rs
- src/util.rs
This PR adds a brand new, type-preserving pass that gets rid of all global variables by tuning them into functions.
This does not yet resolve the issue about declare: #334 
Example:
```
(let x 3)
(Add x x)
```
becomes
```
(function x () i64)
(set (x) 3)
(Add (x) (x))
```
Most of this PR is helpers, such as `map_exprs`, which allows us to map over all exprs in the whole egglog program.
Here are some questions we need to resolve before this is merged:
> Desugar global variables away

- src/ast/desugar.rs
- src/ast/mod.rs
- src/ast/remove_globals.rs
- src/constraint.rs
- src/core.rs
- src/function/mod.rs
- src/lib.rs
- src/main.rs
- src/typechecking.rs
- src/util.rs
- tests/files.rs
This PR allows different code to set different reserved symbols for the symbol gen struct
This fixes all of our name conflicts. Desugaring using `__` by default and the middle of the compiler uses `$`
> Symbol generation fixes

- src/ast/desugar.rs
- src/ast/mod.rs
- src/ast/parse.lalrpop
- src/gj.rs
- src/lib.rs
- src/typechecking.rs
- tests/combined-nested.egg
- tests/test-combined-steps.egg
- tests/test-combined.egg
This PR adds combined rulesets to egglog, allowing rulesets to be collected and run together.
We plan to use this feature in eggcc, since we declare a ruleset per optimization. We want all our optimizations to run together each iteration.
The PR also cleans up the main loop of egglog, breaking it into functions.
Finally, it deletes the backoff scheduler functionality, which nobody uses as far as I can tell.
> Add combined rulesets to egglog

- src/lib.rs
This PR adds an error message when the ruleset does not exist.
```
// Before
called `Option::unwrap()` on a `None` value 
// After
test panicked: ruleset does not exist: wrongnameruleset
```
> Add error message for ruleset that DNE.

- src/lib.rs
Currently with the graphviz output, all leaves will be inlined. This makes the graph a bit more compact, but end up with a representation that is less true to the source, by adding function calls in single nodes with a `f(*args)` calling convention.
Without the inlining it would resolve this complaint from [a blog post](http://www.chriswarbo.net/blog/2024-02-25-sk_logic_in_egglog_1.html):
> Note: Yes, it’s annoying that the graphical output writes parentheses like E("C"), whilst the actual egglog language uses prefix-style (E "C"). That seems to be a quirk of the rendering; all of the actual code will always use the latter style!
---
Alternatively, we could add an option in the serialization for inling leaves but keeping the format as s-expressions. That could be useful to explore in the …
> Change graphviz output to not inline leaves

- src/lib.rs
Being able to read in f64 fields would be quite useful. If this initial implementation seems reasonable enough I'd be happy to add a test or two ...
> Accept f64 function arguments in `(input ...)`

- src/sort/fn.rs
- tests/unstable-fn.egg
This resolves #382 by adding parsing support for defining sorts of 0 argument unstable functions.
It does this by handling that input `()` as the `Unit` constructor.
If we ever want to remove the Unit constructor, we could move the return type to the list of argument types, to make sure it always has at least one value.
This would also make parsing it more similar to other datatypes.
For now I just kept it the same to make the change minimal.
> Fix support for nullary unstable functions

- src/serialize.rs
Previously, if certain nodes were omitted due to size constraints in the serialization format, than they would not appear at all and the edge to them would be missing as well.
This was confusing, because then some functions would have the wrong number of arguments.
Now, if an edge points to an e-class where all nodes in that e-class were omitted, a dummy `[...]` node is added to that e-class so that they have something to point to.
Previously, we discussed implementing this change by modifying the serialization format to allow pointing to `null` node IDs as children. I went with this approach here, by just creating omitted dummy children, so you can still know the sort of the omitted node and if two nodes point to the same omitted e-class, that will also be visible.
Example of omitted …
> Serialize edges to omitted nodes

- src/constraint.rs
- src/core.rs
- src/lib.rs
- src/sort/fn.rs
- src/typechecking.rs
- tests/fail-typecheck/unstable-fn-wrong-args-type.egg
- tests/fail-typecheck/unstable-fn-wrong-return-type.egg
- tests/unstable-fn.egg
Previously, the type inference for creating function values with `(unstable-fn <name> [<partial arg>]*)` did not use the name. It would only use the context within which the function was created to infer the type of the function.
This works fine if you only have one function sort defined or if always can infer it based on its calling location. However, I was noticing in my usages of `unstable-fn` I would often be passing another function reference as a partial arg. This means it would be hard for the type checker to figure out what type to use for these, so it would just give up and fail.
In this PR, I extend the type inference for functions to use the string name. If it is a literal value that shows up during type checking and we can find it in the function table, we use this to help …
> Infer types of functions values based on names

- src/lib.rs
- src/main.rs
Currently, the REPL mode evaluates programs line by line, which means `egglog < main.egg` almost certainly won't work because most expressions are multi-lines. Moreover, simply concatenating all lines in the source file (e.g., `tr -d "\n" < main.egg | egglog`) also does not work if the source file contains comments.
This PR fixes this by only evaluating a multi-line block when all the parentheses are closed. So that the program
```
(extract "1
2
3 
)
"
) (extract
";;;""))"
)
```
will only call `parse_and_run_program once` once at the end of the program
> In REPL, evaluates only when parens are closed

- src/ast/mod.rs
For custom sorts out of core it is useful to have these defined for `make_expr`.
Follow up on #389
> Make dummy span and filenames public

- .gitignore
- Cargo.lock
- Cargo.toml
- Makefile
- src/lib.rs
- src/main.rs
- src/serialize.rs
- src/sort/set.rs
- src/sort/vec.rs
- tests/files.rs
- web-demo/src/lib.rs
This PR moves the ability to split primitive nodes into the serialize library from this library and also extends it to support splitting arbitrary nodes. See https://github.com/egraphs-good/egraph-serialize/pull/14 for the upstream PR that corresponds to this one, which includes an example using this new behavior.
By default, this should result in the same behavior as before, but just with the ability to split more e-classes besides just primitive nodes if desired.
In order to move the splitting logic upstream, I exposed a way to check if a serialized node ID is a primitive. In a way, this extends https://github.com/egraphs-good/egglog/pull/396 by also now supporting public deserialization/serialization for serialized node IDs as well as class IDs. This should also be useful if you do …
> Move splitting primitives to serialize library

- src/actions.rs
- src/function/mod.rs
- src/lib.rs
- src/sort/fn.rs
This PR removes the `type_info` and `type_info_mut` from the `EGraph` struct, since having a mutable getter that doesn't do anything else doesn't make sense.
Happy to close this PR if there is a reason for these functions, but only if that reason is documented.
> Remove useless type_info getters

- src/lib.rs
This PR removes `HIGH_COST` for a few reasons:
1. It's unused.
2. It's buggy. On 32-bit systems (such as WASM?) `i64::MAX` will overflow.
3. It's undocumented, so I don't believe it's used outside of this crate. If it is used outside of this crate, I'll edit the PR to use `isize` instead of `i64` to fix the bug, and add documentation.
> Remove HIGH_COST

- src/ast/desugar.rs
- src/ast/mod.rs
- src/lib.rs
This PR moves the `ProgramParser` struct out of `Desugar` and into a `lazy_static` block. This has a couple of benefits.
1. Separation of concerns
2. We won't clone the parser (which is apparently slow) when we `push`
> Static parser

- src/ast/desugar.rs
- src/constraint.rs
- src/core.rs
- src/function/mod.rs
- src/lib.rs
- src/sort/fn.rs
- src/typechecking.rs
- src/util.rs
This PR:
1. Deletes the unused `_special` methods on `SymbolGen`.
2. Deletes the `ResolvedGen` struct and just `impl FreshGen for SymbolGen` twice.
3. Creates one `SymbolGen` in `EGraph` that is used everywhere, instead of constructing multiple `SymbolGen`s which is potentially buggy.
> SymbolGen cleanup

- src/ast/desugar.rs
- src/lib.rs
This PR cleans up `ast/desugar.rs`, now that we've moved both the parser and the symbol generation out of the `Desguar` struct.
More specifically, this PR:
1. Deletes the `Desugar` struct. (We also discussed doing something like `struct Desugar(&mut SymbolGen)`, but I don't want to do this unless we have at least two things inside the struct.)
2. Deletes the `desugar::get_fresh` function, as I think that we should instead give name hints to `SymbolGen` that indicate where the variable was generated from.
3. Deletes `desugar_commands`, as without the `Desugar` struct this is exactly the same as `desugar_program` (which I've moved to the top of the file as the entry point).
> Delete desugar struct

- src/lib.rs
Update the `extract_value` comment due to Yihong's observation that the set of nodes in the `TermDag` is not always equal to the set of nodes in the `Term`.
> `extract_value` documentation

- Cargo.lock
- web-demo/Cargo.toml
- web-demo/src/lib.rs
- web-demo/static/index.html
- web-demo/static/worker.js
This PR adds the ability to try the [new interactive visualizer](https://github.com/saulshanabrook/egraph-visualizer) in the web editor. I still kept the original graphviz visualizer as default, while this while let you switch between them:
https://github.com/user-attachments/assets/820529fe-d56c-46f7-a5bc-34b5f157b1a3
The new visualizer includes the following features compared to the existing editor:
- Hopefully, better performance when laying out and rendering many nodes
- The ability to focus on a single sub-graph, by clicking on a node and filtering to its descendants
- highlights the connected components to an edge/node on click (could add an on-hover option as well)
- incremental layout based on the existing positions, which the layout engine will take into account
- preserving …
> Add support for the interactive visualizer

- src/actions.rs
- src/ast/expr.rs
- src/ast/remove_globals.rs
- src/constraint.rs
- src/core.rs
- src/lib.rs
- src/sort/bool.rs
- src/sort/f64.rs
- src/sort/fn.rs
- src/sort/i64.rs
- src/sort/macros.rs
- src/sort/map.rs
- src/sort/mod.rs
- src/sort/rational.rs
- src/sort/set.rs
- src/sort/string.rs
- src/sort/unit.rs
- src/sort/vec.rs
- src/typechecking.rs
1. Removes `name` from basic sorts.
2. Removes unconditional `get_sort`.
3. Adds `Presort` trait.
4. Removes basic sorts from being stored in primitives.
5. Removes unused and undocumented macros.
6. Makes `Rational` set lazy static.
> Sort declaration cleanup

- src/sort/multiset.rs
The `Value.tag` PR passed CI when it shouldn't have. This PR fixes the compiler error currently on `main`.
> Fix multiset after `Value.tag`

- Cargo.lock
- Cargo.toml
- src/sort/bigint.rs
- src/sort/bigrat.rs
- src/sort/i64.rs
- src/sort/macros.rs
- src/sort/mod.rs
- src/sort/rational.rs
- src/typechecking.rs
- tests/bignum.egg
This PR adds `BigInt` and `BigRat` sorts by external demand. This PR does not add significant complexity to the codebase, as both `BigInt` and `BigRat` are implemented the same way as we've implemented `Rational`.
As a side effect, this PR also:
- consolidates our dependency on `num` for `BigInt`
- fixes a bug in the `add_primitives` macro to allow for arguments of different types
- adds a very very small test
> `BigInt` and `BigRat`

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Cargo.toml
This PR enables incremental builds for release mode to speed up hot runs of `make test`. It also turns off incremental builds in CI, following the advice of [this blog post](https://fasterthanli.me/articles/why-is-my-rust-build-so-slow#:~:text=Generally%20I%20would%20advise%20setting%20incremental%20%3D%20true%20in%20profile.release%2C%20and%20just%20disabling%20it%20in%20CI%20by%20setting%20the%20environment%20variable%20CARGO_INCREMENTAL%20to%200.).
> Speed up local `make test` runs

- Cargo.toml
- web-demo/Cargo.toml
`egraph-serialize`'s "serde" and "graphviz" features are not used in the library but are always enabled. Disable them by default and extract them into our own features that just delegate to `egraph-serialize` to preserve the functionality.
This is a breaking change for library users that disable default features.
> Extract egraph-serialize features

- src/sort/multiset.rs
- tests/multiset.egg
`multiset-sum` combines values from both multisets together, allowing for rules such as
```
(rewrite (Add (Sum  xs) (Sum ys)) (Add (Sum (multiset-sum xs ys))))
```
In my understanding, this primitive is crucial for modelling associative + commutative operations with multisets, but I might be missing something.
> Add multiset-sum primitive

- src/ast/parse.rs
Minor performance improvement for the parser. In `repeat_until_end_paren` the `Err` is constructed and discarded immediately after, which allocated a string unnecessarily.
> Store str instead of String in ParseError

- Cargo.toml
- build.rs
The build script is only used for emitting the `FULL_VERSION` environment variable, which is only used in the binary. Make it a noop if "bin" is not enabled.
> Disable build script for library builds

- src/ast/parse.rs
This reverts commit 4c280616db0b1bf2bb850aab0075c8f83acd5f33.
Fixes https://github.com/egraphs-good/egglog/issues/468.
Supersedes https://github.com/egraphs-good/egglog/pull/470.
> Revert "Change map to be a trait method"

- src/gj.rs
To see how this bug can cause failures, comment out the lines where `from_column_index` is used (which is hiding the bug) and use `LazyTrie::default` instead and run the tests again.
> Fix the missing `include_subsume` flag so that subsumed tuples does not show up for rules

- src/ast/parse.rs
Calling `Display` on `DUMMY_SPAN` used to crash the program in debug mode due to underflow. No longer.
> Fix display implementation for DUMMY_SPAN

- src/actions.rs
- src/ast/desugar.rs
- src/ast/expr.rs
- src/ast/mod.rs
- src/ast/parse.rs
- src/ast/remove_globals.rs
- src/constraint.rs
- src/lib.rs
- src/sort/f64.rs
- src/sort/mod.rs
- tests/cyk.egg
Fixes #488.
Implements an S-expression based parser, greatly improving error messages in the process. For example, we now print usage strings if the parser is unable to recognize a specific command.
> S-Expression based parser

- src/function/table.rs
Avoid unnecessary monomorphization due to macro inlining of closures. This can't always be a method because of double borrows when searching mutably.
> Implement search_for! using functions

- src/termdag.rs
[Zulip](https://egraphs.zulipchat.com/#narrow/channel/375765-egg.2Fegglog/topic/bottleneck.20in.20run_program.20function)
Current version of `TermDag::to_string` caches a string for each DAG node. This results in quadratic memory blowup (these strings contain each other) which prevents vector benchmark from running on my machine.
This PR fixes the issue by building one result string and using string ranges to refer to already built substrings. Memory consumption should now be proportional to the length of the string. This also avoids quite a few allocations.
With these changes I am finally able to run the benchmark (it used to OOM for me). In conjunction with the other PR, full running time is now under a second.
> Avoid quadratic memory blowup in TermDag::to_string

- src/extract.rs
- src/lib.rs
- src/serialize.rs
- src/sort/bigint.rs
- src/sort/bigrat.rs
- src/sort/bool.rs
- src/sort/f64.rs
- src/sort/fn.rs
- src/sort/i64.rs
- src/sort/map.rs
- src/sort/mod.rs
- src/sort/multiset.rs
- src/sort/set.rs
- src/sort/string.rs
- src/sort/unit.rs
- src/sort/vec.rs
[Zulip thread](https://egraphs.zulipchat.com/#narrow/channel/375765-egg.2Fegglog/topic/bottleneck.20in.20run_program.20function)
This fixes a part of the issue in #492 not concerning stringification. Original test still doesn't run on my computer due to a crash in `TermDag::to_string` (I suspect I don't have enough memory?)
The main contribution here is making extraction for `Sorts` return a `Term` instead of `Expr`. This cuts down the extraction time significantly. I was able to verify this by replacing extraction command with `(extract 1)` in the original test case (this is a meaningful test case since extract command still computes optimal extraction for *all* e-classes).
Ideally this would also get rid of `is_eq_sort` checks by moving that logic to the `extract_expr` for `EqSort`. …
> Refactor sort extraction API

- src/function/table.rs
Small performance gain since the generic From/Extend implementations do not (cannot) specialize on Copy vs Clone types.
> Use SmallVec::from_slice instead of .into()

- Cargo.lock
- Cargo.toml
- src/ast/desugar.rs
- src/ast/expr.rs
- src/ast/mod.rs
- src/ast/parse.rs
- src/core.rs
- src/function/mod.rs
- src/lib.rs
- src/sort/fn.rs
- src/termdag.rs
This PR adds a `Macros` struct that can be used to extend the parser from external crates. This introduces a name conflict with the existing public `Sexp` dependency. Since I don't believe that we need this dependency, I have removed it, which breaks all of the code that depends on the `ToSexp` trait, which is basically just resugaring. Since I do not see the value in resugaring I have removed it. However, I am open to having my mind changed on resugaring, in which case I will reimplement `Display` for the affected structs without using `ToSexp`.
> Make parser extensible

- src/lib.rs
Rule names were previously ignored due to a mistake in desugaring. No more!
[Simple repro](https://egraphs-good.github.io/egglog/?program=XQAAgAB-AAAAAAAAAAAUGQgnfMUD9dO1z5tXL2V7YXwuMzFgetbWNpK1v545cybgIYFxXuXImLjr-e9Z3XLAFZO76y0A1XWNcAiy8dwWQ74D_a5qlrtqw1i83DA0d39yhk_ruUX_3q4AAA%253D%253D)
```
(datatype A (B) (C) (D))
(rule () ((union (B) (C))))
(rule () ((union (C) (D))) :name "cd")
(let b (B))
(run 1)
(print-stats)
```
Current output:
```
Overall statistics:
Rule (rule ()       ((union (B ) (C )))          ): search 0.000s, apply 0.000s, num matches 0
Rule (rule ()       ((union (C ) (D )))          ): search 0.000s, apply 0.000s, num matches 0
Ruleset : search 0.000s, apply 0.000s, rebuild 0.000s
```
New output:
```
Overall statistics:
Rule (rule ()       ((union (B ) (C ))) …
```
> Preserve rule names

- src/ast/expr.rs
- src/ast/parse.rs
- src/constraint.rs
- src/extract.rs
- src/lib.rs
- src/serialize.rs
- src/sort/fn.rs
- src/termdag.rs
- src/typechecking.rs
- tests/integration_test.rs
This PR improves error messages by introducing two new types of spans. The first is `Span::Rust`, which stores a location in a Rust file using [the `file!` macro family](https://doc.rust-lang.org/std/macro.file.html). The second is `Span::Panic`, which can be used when you know that the span should not be introspected; for an example, see the changes in `serialize.rs`.
> Replace `DUMMY_SPAN` with `Span::Panic` and `Span::Rust`

- src/lib.rs
It's currently impossible to define custom sorts outside of `egglog` due to the fact that types like `Extractor` and `Cost` aren't exposed. This PR fixes this by exposing `extractor` module.
The module is already using `pub` and `pub(crate)` in all the right places. I do wonder however if `costs` field of the `Extractor` needs to be public
> Expose extraction module publicly

- src/sort/i64.rs
i64 primitives handle overflow with wraparound in Release mode and panic in Debug mode. This PR makes wraparound behavior consistent across compilation modes.
(Side note: I didn't know shift operations can fail. Would it be a good idea to add a wrapping version for them?)
PS: took me some time to sort out git situation after unsuccessful rebase, sorry about that.
> Fix the behaviour of i64 primitives on overflow

- src/sort/macros.rs
This macro fails to expand if you don't import `std::sync::Arc` at invocation site.
> Fix non-hygienic mention of Arc in add_primitives macro

- src/ast/desugar.rs
- src/ast/parse.rs
- src/lib.rs
- src/termdag.rs
This PR does a few small things:
* Make parsing-related functions public and make them member functions of Parser
* Make the macro type a trait- the current macro type is defined as a `fn`, which has to be static (e.g., no captured values from the environment nor dynamic behavior)
* Add a few convenience methods so it's usable from outside the crate
> Polish the macro interface

- src/ast/parse.rs
- src/lib.rs
- src/main.rs
- src/repl.rs
This PR should subsume #486 by exposing the repl functionality of egglog as a public function. Compared to #486, this handles for multi-line commands and does not introduce duplicate code.
Other minor changes:
* Fix a bug with the parser where input consisting of newline characters cause the parser to fail (see [this program](https://egraphs-good.github.io/egglog/?program=XQAAgAADAAAAAAAAAAAFaD3_____4AAAAA%253D%253D) ).
* Move implementation for `interactive_mode` to `run_commands` for correct handling, since the previous logic for `interactive_mode` assumes one command per line and just prints `(done)` for each line of the input.
> Expose egglog REPL as a function

- src/sort/bigrat.rs
- tests/rat-pow-eval.egg
This also changes the behavior of 0^0 to be 1
as opposed to undefined
> Impls BigRat `pow` for negative powers

- src/sort/set.rs
This PR addresses my issue #512, which was about the inconsistency between Sets and MultiSets. <br>
I changed the `extract_term` logic of Sets to the same of MultiSets. This works for me, but I am not sure if this takes everything into account.
> [#512] set-of instead of set-insert

- src/ast/parse.rs
- src/function/mod.rs
- src/gj.rs
- src/lib.rs
We can make the EGraph implements the `Send` trait by substituting some of the components with thread-safe alternatives so this works:
```
lazy_static! {
pub static ref RT: Mutex<EGraph> = Mutex::new(EGraph::default());
}
```
> Thread-safe EGraph struct

- src/ast/parse.rs
This PR makes public the fields on the egglog span so that we can access them from the Python bindings. In Python, I have been generally converting to/from egglog sructs by creating a corresponding Python class and copying all of their fields. To do so , it has to be public.
I also use the debug formatting to allow pretty printing in Python as the rust struct.
See https://github.com/egraphs-good/egglog-python/pull/258 for the corresponding PR on the Python side.
> Expose EgglogSpan publicly and add debug to spans

- Cargo.lock
- Cargo.toml
- src/function/mod.rs
- src/lib.rs
This PR doesn't actually work; it causes fewer tests to pass than before. I've looked at the `bignum` test, and it seems to fail by not finding the variable that is returned from a primitive, but I'm not sure how to fix it.
> Fix primitives in queries

- Cargo.lock
- Cargo.toml
- src/lib.rs
Wires subsumption up to the new backend. Passes `subsume.egg` if the `extract`s are removed.
> Subsumption in frontend

- tests/repro-new-backend-delete.egg
- tests/repro-new-backend-prims.egg
Adds a minimized `prims.egg` test and the test from #546.
Both tests are currently failing.
> Add repro-new-backend tests

- src/cli.rs
Closes https://github.com/egraphs-good/egglog/issues/550 by adding more context if IO errors fail in the CLI. Makes sure to mention dot must be installed if creating an SVG fails.
> Add more context to IO errors in CLI

- src/ast/parse.rs
Thanks to @FTRobbin for finding this; on line 652 of `parse.rs`, we were flattening a `Result` iterator instead of propagating the error. This had the effect of silently discarding top-level actions that failed to parse!
I've also added type annotations to the other sites in this file where we use `flatten` to make sure that this isn't happening there.
> Fix parser ignoring errors

- src/lib.rs
- src/unionfind.rs
Currently it's not possible to implement `canonicalize` method of `Sort` trait on container sorts defined outside of this crate due to the use of private `UnionFind` type. This PR exposes `UnionFind` and `Id` types (`Id` was already part of the `union` method on e-graph). The only publicly accessible method on `UnionFind` is `find` (since it already has public EGraph counterpart).
> Make union-find struct externally accessible (for container implementation)

- src/ast/check_shadowing.rs
- src/ast/desugar.rs
- src/ast/mod.rs
- src/ast/parse.rs
- src/cli.rs
- src/lib.rs
- src/typechecking.rs
- tests/eggcc-extraction.egg
- tests/files.rs
- tests/integration_test.rs
- tests/list.egg
1. Makes variables named `_` wildcards in `parse.rs`.
2. Adds a check to forbid shadowing. Fixes one benign case (in `list.egg`) and one bug (in `eggcc_extraction.egg`).
3. Adds span info to the ruleset commands.
4. Made the rewrite desugaring use the symbol gen.
5. Deleted the "reserved symbol" command line argument, and the `EGraph::set_reserved_symbol` method.
Fixes #329, #556, #409.
> Underscores, shadowing, and misc.

- web-demo/static/index.html
Fixes https://github.com/egraphs-good/egglog/issues/551 by using `textContent` instead of `innerHTML` in the web demo so that content is properly escaped. As [recommended by MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations)
> Fix web demo escaping

- src/actions.rs
- src/ast/desugar.rs
- src/ast/mod.rs
- src/ast/parse.rs
- src/constraint.rs
- src/core.rs
- src/extract.rs
- src/lib.rs
- src/typechecking.rs
- changed the asts
+ had to make `query-extract` a first-class command instead of desugaring it away, but it should be a combination of `check` and regular `extract`
- fixed desugaring
- fixed typechecking
- factored out eval_resolved_expr_new from the output command so that the extract command can use it
still todo:
- implement the extractor
- implement query-extract
- implement eval_resolved_expr_old (or you can implement the old extractor some other way)
> no action extraction in progress

- src/lib.rs
Previously, the push implementation cloned the entire egraph... including previously pushed egraphs
So a sequence of n pushes took `O(n^2 * size_of_initial_egraph)` space
This PR fixes that so it takes n * size_of_initial_egraph space
> Much Faster Push Implementation

- .github/workflows/build.yml
As described in the [codspeed discussion](https://discord.com/channels/1065233827569598464/1370395084251467869), the benchmarks should only be run on `main` and on PRs, not on other branches, or else the changes will get confused on the PRs:
> Hello, it seems you are running the CodSpeed action both on push and on pull_request (See the workflow file). This creates an inconsistency on our end, because we have a different logic depending on the event type.
> In particular, the push-related runs are compared to the previous commit on the same branch, whereas the pull_request runs are compared to the base branch (what you would expect in your situation).
> 
> I would advise to create a separate workflow file to run your CodSpeed benchmarks, with a config similar to what is described in our …
> Fix Codspeed Comparisons

- src/actions.rs
- tests/subsume-relation.egg
This PR de-duplicates code for fresh output generation, fixing a bug with relation subsumption: old code for subsume just grabbed a new value from UF, which is not the right way to generate outputs for relations.
Let me know if `NewOutputGen` stuff is too much - I can do a simpler version going directly to a new fresh `Value` (it would be less code, but it would require an extra unwrap() call).
> Fix value generation for relations in Change::Subsume code

- src/lib.rs
Running rebuilding before running the commands means that the results from the Rust API would be wrong after running e.g. a top level `union`.
This is an old backend/v0.5 kind of fix.
> Rebuild after running commands instead of before

- src/lib.rs
This PR reimplements `function_to_dag` and fixes `print_function`.
The new `function_to_dag` accepts an additional parameter for whether to extract the output column and returns a 3-tuple of a vector of terms corresponding to the function rows (enodes), an optional vector of terms corresponding to the function outputs (classes), and a termdag.
> `function_to_dag`

- src/extract.rs
- src/lib.rs
- src/sort/fn.rs
- src/sort/mod.rs
This PR:
1. Added more documentation to the trait
2. Moved default cost functions from the sorts into the default cost model
2.1. Changed the default cost for unstable-fn from `1 + sum of children's costs` to just `sum`
3. Made the cost model interface generic
4. Made the extractor interface generic to the cost type with `Cost: SaturatingAdd + Zero + One + Ord + Eq + Copy + Debug`
> Tweaking `CostModel` Trait

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/prelude.rs
- src/sort/mod.rs
This PR optimizes `input_file` performance. Instead of creating as many top-level commands as rows in the csv file, this implementation uses a single rule with a custom callback that inserts all the rows with `TableAction`.
> Improve `input_file` performance

- src/prelude.rs
Question: Should they be macros? I think macros will allow us to expand and inject the correct line information with `span!` instead of being in `prelude.rs`
> Include more literals in prelude

- src/lib.rs
- src/serialize.rs
This PR changes the behavior of extract when it is a primitive sort and it does not exist, so that it does not panic but raises an error instead.
This was the previous behavior on the old backend and it was relied on by the Python bindings. They used this fact to try extracting a term, and only if it doesn't exist, then run some rules to create it (https://github.com/egraphs-good/egglog-python/blob/b8be0848e22137396f31f86a73c447f4997f68fe/python/egglog/exp/array_api.py#L1973-L1985).
The alterantive of using `check` and then extracting is slower especially when the terms are large. Currently, it will panic and catching a panic in Rust and then continuing is not ideal. This PR handles a cleanup as well even if the rule doesn't succeed.
> Don't panic when extracting non existent term

- Cargo.lock
- Cargo.toml
- src/core.rs
- src/serialize.rs
- src/typechecking.rs
Desugar `rewrite`s into calls to `set` where possible. Also bump the egglog-backend version.
* This speeds a lot of stuff up as it avoids creating a new Id that needs to be rewritten later
* The PR handles the case where such a rewrite is impossible and we need to keep `union` around.
* The current implementation of proofs needs to support minting new Ids in this case anyway. We shouldn't pessimize rules run without proofs just for proofs to work.l
Fixes #350
> Union=>set desugar

- Cargo.toml
- src/cli.rs
- src/main.rs
Speeds up CLI by using options in benchmark mode of a custom allocator and reducing the number of threads.
Locally, this decreased the time of running `time ./target/release/egglog tests/no-messages/python_array_optimize.egg --no-messages` from about 6 seconds to 3 seconds after running `cargo build --release`.
We could add more options in the future to configure these things from public API, but for now I wanted to at least speed up performance so we can better profile things in the CLI and have it be representative.
> Speedup CLI

- src/cli.rs
```
% time target/release/egglog  /tmp/cykjson-big.egg
[INFO ] Declared sort tree.
[INFO ] Declared function NT.
[INFO ] Declared function T.
[INFO ] Declared function getString.
[INFO ] Declared function Prod.
[INFO ] Declared function End.
[INFO ] Declared function P.
[INFO ] Declared function B.
[INFO ] Declared rule (rule ((End a s)
(= s (getString pos)))
((P 1 pos a)
(set (B 1 pos a) (T a s)))
).
[INFO ] Declared rule (rule ((Prod a b c)
(P p1 s b)
(P p2 (+ s p1) c))
((P (+ p1 p2) s a))
).
[INFO ] Declared rule (rule ((Prod a b c)
(= f1 (B p1 s b))
(= f2 (B p2 (+ s p1) c)))
((set (B (+ p1 p2) s a) (NT a f1 f2)))
).
[INFO ] Opening file '"./tests/cykjson_Prod.csv"'...
[INFO ] Read 17 facts into Prod from './tests/cykjson_Prod.csv'.
[INFO ] Opening file '"./tests/cykjson_End.csv"'... …
```
> add parallelism flag

- Cargo.toml
- src/core.rs
- src/util.rs
We no longer rely on `Symbol` in the frontend, so this doesn't do anything. We _hypothesize_ that the new backend is deterministic if parallelism is disabled.
> remove "nondeterminism" flag

- benches/common.rs
- src/cli.rs
- src/serialize.rs
- tests/files.rs
- tests/integration_test.rs
Implement functionality to indicate when serialization exceeds specified limits, enhancing user feedback during serialization processes. Fixes #643
> Expose whether serialization is cut off, fixes #643

- Cargo.toml
- src/main.rs
Currently building egglog is failing for the web demo because of an issues installing the mimalloc allocator (https://github.com/egraphs-good/egglog-demo/actions/runs/17182776958/job/48747498611)
I also had issues building mimalloc in CI when building one target of the Python bindings.
This PR changes mimalloc to only be a bin dependency, so its not installed when just installing the package.
> Only install mimalloc for bin

- src/ast/mod.rs
- src/lib.rs
Closes https://github.com/egraphs-good/egglog/issues/656 by logging properly what kind of function is declared, whether its a relation, constructor, or function.
Before:
```bash
$ cargo run -- tests/subsume-relation.egg
Compiling egglog v0.5.0 (/Users/saul/p/egg-smol)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.50s
Running `target/debug/egglog tests/subsume-relation.egg`
[INFO ] Declared sort V.
[INFO ] Declared function A.
[INFO ] Declared function B.
[INFO ] Declared function C.
[INFO ] Declared function R.
[INFO ] Checked fact [Eq(In 9:8-25 of tests/subsume-relation.egg: (= (R (A) (B)) ()), Call(In 9:11-21 of tests/subsume-relation.egg: (R (A) (B)), Func(FuncType { name: "R", subtype: Relation, input: [EqSort { name: "V" }, EqSort { name: "V" }], output: …
```
> Log proper function type instead of calling them all "function"

- src/cli.rs
- src/lib.rs
Emits a `> ` prompt and the welcome message when running from the CLI with no file inputs and no stdin piped.
Adds a test for this mode in the repl tests.
```
$ ./target/debug/egglog
Welcome to Egglog REPL! (build: 1.0.0_2025-09-10_34c2f2de)
> (extract 10)
10
> ^C⏎
$ echo '(extract 1)' | ./target/debug/egglog
1
```
Follow up of #659 now that INFO is not printed by default.
> Emit prompt and debug info when running from REPL

- src/scheduler.rs
Whenever I build egglog, I get this warning from the rust compiler:
```
+ cargo build --manifest-path egglog/Cargo.toml --quiet
warning: hiding a lifetime that's elided elsewhere is confusing
--> src/scheduler.rs:85:22
|
85 |     pub fn get_match(&self, idx: usize) -> Match {
|                      ^^^^^                 ----- the same lifetime is hidden here
|                      |
|                      the lifetime is elided here
|
= help: the same lifetime is referred to in inconsistent ways, making the signature confusing
= note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: use `'_` for type paths
|
85 |     pub fn get_match(&self, idx: usize) -> Match<'_> {
|                                                 ++++
```
I don't really know much about rust, but this seems …
> Fixing rust compiler warning
